#Generated by GPT 6 Luna


"""Reusable side-by-side iframe wrapper for Viser scenes."""

from __future__ import annotations

import html
import threading
import webbrowser
from dataclasses import dataclass
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Sequence
from urllib.parse import urlparse


@dataclass(frozen=True)
class SceneView:
    """A Viser scene to embed in the split view."""

    title: str
    url: str


class ViserSplitView:
    """Serve a page containing two or more resizable Viser scenes.

    Example:
        split_view = ViserSplitView(
            [
                SceneView("Latent space", "http://127.0.0.1:8080/"),
                SceneView("Decoded space", "http://127.0.0.1:8081/"),
            ],
            port=8082,
        )
        split_view.start(open_browser=True)

        # Later, when shutting down:
        split_view.close()
    """

    def __init__(
        self,
        views: Sequence[SceneView],
        *,
        host: str = "127.0.0.1",
        port: int = 8082,
        min_pane_width_px: int = 180,
    ) -> None:
        if len(views) < 2:
            raise ValueError("ViserSplitView requires at least two views.")

        if min_pane_width_px < 1:
            raise ValueError("min_pane_width_px must be positive.")

        for view in views:
            parsed_url = urlparse(view.url)
            if parsed_url.scheme not in ("http", "https") or not parsed_url.netloc:
                raise ValueError(
                    f"View URL must be an absolute http:// or https:// URL: {view.url}"
                )

        self.views = tuple(views)
        self.host = host
        self.port = port
        self.min_pane_width_px = min_pane_width_px

        self._server: ThreadingHTTPServer | None = None
        self._thread: threading.Thread | None = None

    @property
    def url(self) -> str:
        """URL for the wrapper page."""
        return f"http://{self.host}:{self.port}/"

    def _make_html(self) -> bytes:
        panes = []

        for index, view in enumerate(self.views):
            title = html.escape(view.title, quote=True)
            url = html.escape(view.url, quote=True)

            panes.append(
                f"""
                <iframe
                    title="{title}"
                    src="{url}"
                    allow="fullscreen"
                ></iframe>
                """
            )

            if index < len(self.views) - 1:
                panes.append(
                    f"""
                    <div
                        class="divider"
                        role="separator"
                        aria-label="Resize adjacent scenes"
                        aria-orientation="vertical"
                        tabindex="0"
                        data-index="{index}"
                    ></div>
                    """
                )

        pane_count = len(self.views)
        html_page = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Viser Split View</title>
  <style>
    html, body {{
      width: 100%;
      height: 100%;
      margin: 0;
      overflow: hidden;
      background: #171a20;
    }}

    #layout {{
      display: grid;
      grid-template-columns: repeat({pane_count}, minmax(0, 1fr));
      width: 100%;
      height: 100%;
    }}

    iframe {{
      width: 100%;
      height: 100%;
      min-width: 0;
      border: 0;
      background: #20242b;
    }}

    .divider {{
      position: relative;
      z-index: 2;
      width: 8px;
      background: #343a46;
      cursor: col-resize;
      touch-action: none;
    }}

    .divider:hover,
    .divider.dragging {{
      background: #ff7043;
    }}

    .divider::after {{
      content: "";
      position: absolute;
      top: 50%;
      left: 50%;
      width: 3px;
      height: 42px;
      border-radius: 3px;
      background: #aeb8c8;
      transform: translate(-50%, -50%);
    }}

    .divider:hover::after,
    .divider.dragging::after {{
      background: white;
    }}
  </style>
</head>
<body>
  <main id="layout">
    {''.join(panes)}
  </main>

  <script>
    const layout = document.getElementById("layout");
    const paneCount = {pane_count};
    const dividerWidth = 8;
    const minPaneWidth = {self.min_pane_width_px};
    const weights = Array(paneCount).fill(1);
    const dividers = [...document.querySelectorAll(".divider")];

    function applyWeights() {{
      const tracks = [];

      for (let i = 0; i < paneCount; i++) {{
        tracks.push(`${{weights[i]}}fr`);
        if (i < paneCount - 1) tracks.push(`${{dividerWidth}}px`);
      }}

      layout.style.gridTemplateColumns = tracks.join(" ");
    }}

    function resizeAdjacentPanes(dividerIndex, clientX) {{
      const bounds = layout.getBoundingClientRect();
      const availableWidth =
        bounds.width - dividerWidth * (paneCount - 1);

      if (availableWidth <= 0) return;

      let panesBefore = 0;
      for (let i = 0; i < dividerIndex; i++) {{
        panesBefore += weights[i];
      }}

      const adjacentWeight =
        weights[dividerIndex] + weights[dividerIndex + 1];
      const leftEdgeFraction = panesBefore / weights.reduce((a, b) => a + b, 0);
      const adjacentFraction =
        adjacentWeight / weights.reduce((a, b) => a + b, 0);

      const pointerFraction =
        (clientX - bounds.left - dividerWidth * dividerIndex) / availableWidth;

      const localFraction =
        (pointerFraction - leftEdgeFraction) / adjacentFraction;

      const minLocalFraction = Math.min(
        0.45,
        minPaneWidth / Math.max(1, availableWidth * adjacentFraction)
      );
      const leftLocalFraction = Math.max(
        minLocalFraction,
        Math.min(1 - minLocalFraction, localFraction)
      );

      weights[dividerIndex] = adjacentWeight * leftLocalFraction;
      weights[dividerIndex + 1] =
        adjacentWeight * (1 - leftLocalFraction);

      applyWeights();
    }}

    for (const divider of dividers) {{
      const dividerIndex = Number(divider.dataset.index);
      let dragging = false;

      divider.addEventListener("pointerdown", (event) => {{
        dragging = true;
        divider.classList.add("dragging");
        divider.setPointerCapture(event.pointerId);
        resizeAdjacentPanes(dividerIndex, event.clientX);
        event.preventDefault();
      }});

      divider.addEventListener("pointermove", (event) => {{
        if (dragging) resizeAdjacentPanes(dividerIndex, event.clientX);
      }});

      function stopDragging() {{
        dragging = false;
        divider.classList.remove("dragging");
      }}

      divider.addEventListener("pointerup", stopDragging);
      divider.addEventListener("pointercancel", stopDragging);

      divider.addEventListener("keydown", (event) => {{
        if (event.key !== "ArrowLeft" && event.key !== "ArrowRight") return;

        const bounds = layout.getBoundingClientRect();
        const currentX = divider.getBoundingClientRect().left;
        const amount = event.key === "ArrowLeft" ? -20 : 20;

        resizeAdjacentPanes(dividerIndex, currentX + amount);
        event.preventDefault();
      }});
    }}

    applyWeights();
  </script>
</body>
</html>
"""
        return html_page.encode("utf-8")

    def start(self, *, open_browser: bool = False) -> str:
        """Start serving the wrapper page and return its URL."""
        if self._server is not None:
            return self.url

        page = self._make_html()

        class WrapperHandler(BaseHTTPRequestHandler):
            def do_GET(self) -> None:
                if self.path not in ("/", "/index.html"):
                    self.send_error(404)
                    return

                self.send_response(200)
                self.send_header("Content-Type", "text/html; charset=utf-8")
                self.send_header("Content-Length", str(len(page)))
                self.send_header("Cache-Control", "no-store")
                self.end_headers()
                self.wfile.write(page)

            def log_message(self, _format: str, *_args: object) -> None:
                pass

        self._server = ThreadingHTTPServer((self.host, self.port), WrapperHandler)
        self._server.daemon_threads = True
        self._thread = threading.Thread(
            target=self._server.serve_forever,
            daemon=True,
        )
        self._thread.start()

        if open_browser:
            webbrowser.open(self.url)

        return self.url

    def close(self) -> None:
        """Stop the wrapper server."""
        if self._server is None:
            return

        self._server.shutdown()
        self._server.server_close()

        if self._thread is not None:
            self._thread.join(timeout=2.0)

        self._server = None
        self._thread = None

    def __enter__(self) -> ViserSplitView:
        self.start()
        return self

    def __exit__(self, _exc_type, _exc_value, _traceback) -> None:
        self.close()