#Generated by GPT 6 Luna

# two_scene_viser.py
#
# Keep this file in the same directory as viser_split_view.py.
#
# Install:
#   python -m pip install viser numpy
#
# Run:
#   python two_scene_viser.py
#
# Combined page:
#   http://127.0.0.1:8082/

from __future__ import annotations

import threading
import time

import numpy as np
import viser

from CustomModules.viser_split_view import SceneView, ViserSplitView


LIMIT = 3.0
START_X = 0.8
START_Y = 0.6
POINT_Z_OFFSET = 0.04


def decode(x: float, y: float) -> tuple[float, float, float]:
    """Example mapping from 2D latent coordinates to a 3D surface."""
    return x, y, 0.35 * (x * x - y * y)


def make_surface_point_cloud(resolution: int = 45) -> np.ndarray:
    """Sample points across the example decoded surface."""
    values = np.linspace(-LIMIT, LIMIT, resolution)

    return np.array(
        [
            [x, y, decode(float(x), float(y))[2]]
            for y in values
            for x in values
        ],
        dtype=np.float32,
    )


def main() -> None:
    latent_server = viser.ViserServer(
        host="127.0.0.1",
        port=8080,
        label="2D Latent Space",
    )
    decoded_server = viser.ViserServer(
        host="127.0.0.1",
        port=8081,
        label="3D Decoded Space",
    )

    latent_server.scene.set_up_direction("+z")
    decoded_server.scene.set_up_direction("+z")

    state_lock = threading.RLock()

    # ---------------------------------------------------------------
    # 2D latent scene
    # ---------------------------------------------------------------

    latent_server.scene.add_grid(
        "/latent/grid",
        width=2.0 * LIMIT,
        height=2.0 * LIMIT,
        plane="xy",
        cell_size=0.5,
        section_size=1.0,
        cell_color=(75, 85, 100),
        section_color=(130, 145, 165),
    )
    latent_server.scene.add_label(
        "/latent/x_label",
        "latent x",
        position=(LIMIT - 0.35, -0.48, 0.03),
    )
    latent_server.scene.add_label(
        "/latent/y_label",
        "latent y",
        position=(-0.48, LIMIT - 0.35, 0.03),
    )

    for value in range(-int(LIMIT), int(LIMIT) + 1):
        latent_server.scene.add_label(
            f"/latent/grid_numbers/x_{value}",
            str(value),
            position=(float(value), -0.18, 0.03),
            font_size_mode="screen",
            font_screen_scale=0.8,
            depth_test=False,
        )
        if value != 0:
            latent_server.scene.add_label(
                f"/latent/grid_numbers/y_{value}",
                str(value),
                position=(-0.18, float(value), 0.03),
                font_size_mode="screen",
                font_screen_scale=0.8,
                depth_test=False,
            )

    latent_point = latent_server.scene.add_icosphere(
        "/latent/point",
        radius=0.14,
        color=(255, 112, 67),
        subdivisions=2,
        position=(START_X, START_Y, POINT_Z_OFFSET),
    )

    latent_server.initial_camera.position = (0.0, 0.0, 9.0)
    latent_server.initial_camera.look_at = (0.0, 0.0, 0.0)
    latent_server.initial_camera.up = (0.0, 1.0, 0.0)

    latent_server.gui.add_markdown(
        "Drag the point or use the sliders. "
        "Coordinates are shared with the 3D scene."
    )
    latent_x_slider = latent_server.gui.add_slider(
        "Latent X",
        min=-LIMIT,
        max=LIMIT,
        step=0.01,
        initial_value=START_X,
    )
    latent_y_slider = latent_server.gui.add_slider(
        "Latent Y",
        min=-LIMIT,
        max=LIMIT,
        step=0.01,
        initial_value=START_Y,
    )
    latent_readout = latent_server.gui.add_markdown("")

    # ---------------------------------------------------------------
    # 3D decoded point-cloud scene
    # ---------------------------------------------------------------

    decoded_server.scene.add_grid(
        "/decoded/grid",
        width=2.0 * LIMIT,
        height=2.0 * LIMIT,
        plane="xy",
        cell_size=0.5,
        section_size=1.0,
        cell_color=(65, 75, 90),
        section_color=(120, 135, 155),
    )
    decoded_server.scene.add_label(
        "/decoded/x_label",
        "decoded x",
        position=(LIMIT, 0.0, 0.0),
    )
    decoded_server.scene.add_label(
        "/decoded/y_label",
        "decoded y",
        position=(0.0, LIMIT, 0.0),
    )
    decoded_server.scene.add_label(
        "/decoded/z_label",
        "decoded z",
        position=(0.0, 0.0, LIMIT),
    )

    for value in range(-int(LIMIT), int(LIMIT) + 1):
        decoded_server.scene.add_label(
            f"/decoded/grid_numbers/x_{value}",
            str(value),
            position=(float(value), -0.18, 0.02),
            font_size_mode="screen",
            font_screen_scale=0.8,
            depth_test=False,
        )
        if value != 0:
            decoded_server.scene.add_label(
                f"/decoded/grid_numbers/y_{value}",
                str(value),
                position=(-0.18, float(value), 0.02),
                font_size_mode="screen",
                font_screen_scale=0.8,
                depth_test=False,
            )
            decoded_server.scene.add_label(
                f"/decoded/grid_numbers/z_{value}",
                str(value),
                position=(-0.18, 0.0, float(value)),
                font_size_mode="screen",
                font_screen_scale=0.8,
                depth_test=False,
            )

    decoded_server.scene.add_point_cloud(
        "/decoded/surface_points",
        points=make_surface_point_cloud(resolution=45),
        colors=(95, 175, 225),
        point_size=0.035,
        point_shape="circle",
        point_shading="flat",
    )
    decoded_server.scene.add_frame(
        "/decoded/axes",
        axes_length=1.0,
        axes_radius=0.015,
    )

    px, py, pz = decode(START_X, START_Y)
    decoded_point = decoded_server.scene.add_icosphere(
        "/decoded/point",
        radius=0.14,
        color=(255, 112, 67),
        subdivisions=2,
        position=(px, py, pz + POINT_Z_OFFSET),
    )

    decoded_server.initial_camera.position = (7.0, -9.0, 7.0)
    decoded_server.initial_camera.look_at = (0.0, 0.0, 0.0)
    decoded_server.initial_camera.up = (0.0, 0.0, 1.0)

    decoded_server.gui.add_markdown(
        "Drag the point or use the sliders. "
        "Coordinates are shared with the 2D scene."
    )
    decoded_x_slider = decoded_server.gui.add_slider(
        "Latent X",
        min=-LIMIT,
        max=LIMIT,
        step=0.01,
        initial_value=START_X,
    )
    decoded_y_slider = decoded_server.gui.add_slider(
        "Latent Y",
        min=-LIMIT,
        max=LIMIT,
        step=0.01,
        initial_value=START_Y,
    )
    decoded_readout = decoded_server.gui.add_markdown("")

    # ---------------------------------------------------------------
    # Synchronize both Viser scenes and their GUI controls
    # ---------------------------------------------------------------

    def update_both_scenes(x: float, y: float) -> None:
        x = float(np.clip(x, -LIMIT, LIMIT))
        y = float(np.clip(y, -LIMIT, LIMIT))
        px, py, pz = decode(x, y)

        readout = (
            f"**Latent:** `x = {x:.2f}`, `y = {y:.2f}`  \n"
            f"**Decoded:** `x = {px:.2f}`, `y = {py:.2f}`, `z = {pz:.2f}`"
        )

        with state_lock:
            latent_point.position = (x, y, POINT_Z_OFFSET)
            decoded_point.position = (px, py, pz + POINT_Z_OFFSET)

            latent_x_slider.value = x
            latent_y_slider.value = y
            decoded_x_slider.value = x
            decoded_y_slider.value = y

            latent_readout.content = readout
            decoded_readout.content = readout

    @latent_point.on_drag
    async def on_latent_point_drag(
        event: viser.SceneNodeDragEvent,
    ) -> None:
        if event.phase in ("update", "end"):
            x, y, _ = event.end_position
            update_both_scenes(x, y)

    @decoded_point.on_drag
    async def on_decoded_point_drag(
        event: viser.SceneNodeDragEvent,
    ) -> None:
        if event.phase in ("update", "end"):
            x, y, _ = event.end_position
            update_both_scenes(x, y)

    @latent_x_slider.on_update
    def on_latent_x_slider(_event) -> None:
        update_both_scenes(latent_x_slider.value, latent_y_slider.value)

    @latent_y_slider.on_update
    def on_latent_y_slider(_event) -> None:
        update_both_scenes(latent_x_slider.value, latent_y_slider.value)

    @decoded_x_slider.on_update
    def on_decoded_x_slider(_event) -> None:
        update_both_scenes(decoded_x_slider.value, decoded_y_slider.value)

    @decoded_y_slider.on_update
    def on_decoded_y_slider(_event) -> None:
        update_both_scenes(decoded_x_slider.value, decoded_y_slider.value)

    update_both_scenes(START_X, START_Y)

    # Collapse each Viser control panel initially; expand its rail to use
    # the sliders and coordinate readout.
    latent_server.gui.main_panel.minimize()
    decoded_server.gui.main_panel.minimize()

    # The wrapper module only embeds the scene URLs and provides the splitter.
    split_view = ViserSplitView(
        [
            SceneView("2D latent scene", "http://127.0.0.1:8080/"),
            SceneView("3D decoded scene", "http://127.0.0.1:8081/"),
        ],
        host="127.0.0.1",
        port=8082,
    )

    try:
        print(f"Combined scene view: {split_view.start(open_browser=True)}")
        print("Drag the divider to change the relative scene widths.")
        while True:
            time.sleep(1.0)
    except KeyboardInterrupt:
        print("\nShutting down.")
    finally:
        split_view.close()
        latent_server.stop()
        decoded_server.stop()


if __name__ == "__main__":
    main()